spring.datasource.url=jdbc:postgresql://localhost:5432/snapfitdb
spring.datasource.username=snapfit
spring.datasource.password=snapfit123
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

jwt.secret=VerySecretKeyForSNAPFITjwtGeneration123456
